### PR TITLE
Bump org.clojure/data.xml dep version to accommodate cognitect/aws-api

### PR DESCRIPTION
**Pull request by kaffein**
Hey @devth 

I just bumped `org.clojure/data.xml` to accommodate `cognitect/aws-api`. I have aligned it with the version documented [here](https://github.com/cognitect-labs/aws-api/blob/master/deps.edn).

can you PTAL
thanks a lot ^^

### CODE REVIEW

**Comment by devth** [comment]
Hey @kaffein looks like there’s a conflict in project.clj

**Comment by kaffein** [comment]
ouchh sorry about that, I will check that out ;)

**Comment by kaffein** [comment]
it should be okay now @devth ;)

thanks

**Comment by devth** [comment]
New version should be building on Travis !

**Pull request merged**
